### ISSUE TITLE
Sending commands that need an answer to a prompt

### ISSUE THREAD

**Issue by diogopdvfreitas** [gmoisio/gmoisio.ale#1]
The issue title is pretty self-explanatory but basically I'm facing issues in answering the prompt when I try to execute a reload command, which in turn doesn't trigger the reload on the device.

Is there anyway this can be done?

**Comment by gmoisio** [comment]
Hi, you can use:

```
        timing: true
        commands:
          - reload from working no rollback-timeout
          - "Y"
```

Regards
