### ISSUE TITLE
adding a getter

### ISSUE THREAD

**Issue by FlorianHeigl** [gmoisio/gmoisio.ale#3]
Hi,

I'd need to add a getter for fetching the model number, and maybe also one that can access LLDP info to find uplink switches.

I haven't understood where or how the getters actually function, and if their info becomes part of the host_vars (I suppose so).

Could you tell me what docs you followed to write the first ones?

Also - i don't understand why they exist vs. a classic gather step, which might be part of my problem...

**Comment by gmoisio** [comment]
Hi Florian, thank you for your contact.
I don't understand your question about documentation.
In this Ansible Collection, I made this experimental facts module to test some way to implement it. The code is in the Python module ale_aos_facts.py but it is not made to evolve in the same way.
It would be better for you to use the ale_aos_command module with some show command to be sure to be able to upgrade the collection later.
In the same way, I don't understand your last question. You cannot make a gather step in Ansible for network switches as the generated Python code is running on localhost.
Best Regards

**Comment by FlorianHeigl** [comment]
Thank you for your answer. I think I understood most, and will try to work with ale_aos_command instead.

**Comment by jefvantongerloo** [comment]
If I understand your question correctly, you could use the textfsm-aos package to parse the ansible ale_aos_command output to structured data. You can find an Ansible example in the readme documentation: [https://github.com/jefvantongerloo/textfsm-aos](https://github.com/jefvantongerloo/textfsm-aos)

**Comment by FlorianHeigl** [comment]
Awesome, thank you. This should help me produce some much higher quality
playbook.

Jef Vantongerloo ***@***.***> schrieb am So., 3. Apr. 2022,
13:28:
